### ISSUE TITLE
MapCSS: improvement ideas

### ISSUE THREAD

**Issue by tyrasd** [tyrasd/overpass-turbo#76]
some ideas from [various](http://www.openstreetmap.org/user/tyr_asd/diary/19043) [sources](http://wiki.openstreetmap.org/wiki/Overpass_turbo/MapCSS#Some_Restrictions).
- [x] text-labels #75
- [ ] line-casings
- [ ] content of the popups (and whether or not to have popups at all)
- [ ] background tiles and overlays
- [ ] feature-as-marker rendering control #30, #258
- [x] line offsets #117
- [ ] layers #118
- [ ] line-cap, line-join
- [ ] z-ordering
- [x] eval for text rendering (like [JOSM](https://josm.openstreetmap.de/wiki/Help/Styles/MapCSSImplementation#TextFontproperties)) (related to #235)
- [ ] implement zoom level [filters](http://wiki.openstreetmap.org/wiki/User_talk:Tyr#Overpass_turbo.2FMapCSS)
- [x] improved label placement #261
- [ ] (?) way direction markers, e.g. for oneway roads (https://help.openstreetmap.org/questions/54584/overpass-get-way-direction)
- [x] expose metadata for mapcss filters #352, #356 
- …

**Comment by jidanni** [comment]
Yes, can't tell direction of ways:
![20230129T120223](https://user-images.githubusercontent.com/1230959/215304301-0fb034c7-f934-4a61-abf0-1cdaf2566539.jpg)

**Comment by jayaddison** [comment]
> * z-ordering

@tyrasd Can you provide a sense for whether this feature might be complicated, and/or any implementation opinions?

(the reason I ask: I was exploring the use of Overpass Turbo to draft OSM-originated, styled maps for a local community group recently; one of the issues I encountered while experimenting with MapCSS rules was that some OSM ways were unexpectedly drawn on top of or underneath other ways -- perhaps due to OSM object order -- and I couldn't determine a way to configure that using the stylesheets.  `z-index` was what occurred to me based on my knowledge of HTML CSS, and then I learned that although an equivalent exists in MapCSS, it isn't yet supported here)
